{
  "formatVersion": "1.1",
  "component": {
    "group": "meili.travel",
    "module": "ux-native-android-sdk",
    "version": "1.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "ux-native-android-sdk-1.7.0.aar",
          "url": "ux-native-android-sdk-1.7.0.aar",
          "size": 5022959,
          "sha512": "a7c516357a17da4f6f51fa376e69d160d7f6b1c14caf85d2a6d21bd436ec3589fd92f1bc627ae0a3b2f50e3d0e6fb928e0fe0587d87ae8a93a1b4ed22e15fab3",
          "sha256": "bd2fd2f99cf8fba83599afa98e8ea5182efa01f92e5c91839acadd48d3eebd0e",
          "sha1": "ba1299421cb6bd14c0b0795237ab445e57759b08",
          "md5": "70f2e29207a44aafa4cba9026a54607e"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-kotlinx-serialization",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.kizitonwose.calendar",
          "module": "compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.mikepenz",
          "module": "multiplatform-markdown-renderer-android",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.github.afreakyelf",
          "module": "Pdf-Viewer",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.ramani-maps",
          "module": "ramani-maplibre",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.maplibre.gl",
          "module": "android-plugin-markerview-v9",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-jvm",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.13.45"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-i18n",
          "version": {
            "requires": "1.0.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "ux-native-android-sdk-1.7.0.aar",
          "url": "ux-native-android-sdk-1.7.0.aar",
          "size": 5022959,
          "sha512": "a7c516357a17da4f6f51fa376e69d160d7f6b1c14caf85d2a6d21bd436ec3589fd92f1bc627ae0a3b2f50e3d0e6fb928e0fe0587d87ae8a93a1b4ed22e15fab3",
          "sha256": "bd2fd2f99cf8fba83599afa98e8ea5182efa01f92e5c91839acadd48d3eebd0e",
          "sha1": "ba1299421cb6bd14c0b0795237ab445e57759b08",
          "md5": "70f2e29207a44aafa4cba9026a54607e"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ux-native-android-sdk-1.7.0-sources.jar",
          "url": "ux-native-android-sdk-1.7.0-sources.jar",
          "size": 503617,
          "sha512": "f08cb88ebbbe276ee9d37d707e63e3abccdb49a47b3a3ae7791a7b22af5317c502c887653affeefeefd2e57a333c4eb8854ffd708d246066ea786e3aa6ec4cc6",
          "sha256": "1eb388afbabb24d393c9efb64802fd328f04f8242017d712b1a72a0c548d5e48",
          "sha1": "42cecf426ba1c4fc3779b6bbef0d994be61f3f53",
          "md5": "062bd8eb9373db6e6c87ae421749dab1"
        }
      ]
    }
  ]
}
