{
  "formatVersion": "1.1",
  "component": {
    "group": "meili.travel",
    "module": "ux-native-android-sdk",
    "version": "1.7.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "ux-native-android-sdk-1.7.2.aar",
          "url": "ux-native-android-sdk-1.7.2.aar",
          "size": 4998954,
          "sha512": "5ddb9c67799f41775eb81ddd42915c0bf9433199b1c52433a7b2b5dc653d47d15b86dbd1f5cd9fdf983d6ac0f20e5e233c0f7cd0d0cc84f9764a0213b7223e17",
          "sha256": "1615fb7bf46081e8e51abd71b1a0633860ca9723b2487f48f0d083e99aae66ff",
          "sha1": "23345493b65c7b7a104a24cff606653f5e7e87ae",
          "md5": "7967b4a5ed86d7ddc29f4774e9b0a598"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-kotlinx-serialization",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.kizitonwose.calendar",
          "module": "compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.mikepenz",
          "module": "multiplatform-markdown-renderer-android",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.github.afreakyelf",
          "module": "Pdf-Viewer",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.ramani-maps",
          "module": "ramani-maplibre",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.maplibre.gl",
          "module": "android-plugin-markerview-v9",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-jvm",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.13.45"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-i18n",
          "version": {
            "requires": "1.0.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "ux-native-android-sdk-1.7.2.aar",
          "url": "ux-native-android-sdk-1.7.2.aar",
          "size": 4998954,
          "sha512": "5ddb9c67799f41775eb81ddd42915c0bf9433199b1c52433a7b2b5dc653d47d15b86dbd1f5cd9fdf983d6ac0f20e5e233c0f7cd0d0cc84f9764a0213b7223e17",
          "sha256": "1615fb7bf46081e8e51abd71b1a0633860ca9723b2487f48f0d083e99aae66ff",
          "sha1": "23345493b65c7b7a104a24cff606653f5e7e87ae",
          "md5": "7967b4a5ed86d7ddc29f4774e9b0a598"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ux-native-android-sdk-1.7.2-sources.jar",
          "url": "ux-native-android-sdk-1.7.2-sources.jar",
          "size": 505803,
          "sha512": "63b428baa14b3c29446eba59247beac94d7456aab28dc7834ed1832308cc95352b582e2db5e37e85a7d8bf7eb56604697d3d5bc06c1591572b0c5a89c13f9510",
          "sha256": "7ba681f42da4c54eed049722c99b46683800942b7cd0472bbfa8a2e281eafece",
          "sha1": "6926a8be05469cc85b894ce435a558ac0f1da002",
          "md5": "1ad361d08d55218003d339e94ca43540"
        }
      ]
    }
  ]
}
