{
  "formatVersion": "1.1",
  "component": {
    "group": "meili.travel",
    "module": "ux-native-android-sdk",
    "version": "1.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "ux-native-android-sdk-1.8.1.aar",
          "url": "ux-native-android-sdk-1.8.1.aar",
          "size": 5234554,
          "sha512": "36045aded3c534e4a06e5db43c434131c6ae6982e617773e772b3d72b9b212658213b7a0ec0bff39bd831b9c9ecd4161766b6b9afb18ba0560ec6d6c9663aeb9",
          "sha256": "35579cc1fe36c276be0fe99ea2a9ef7e077ee4515d9f00fb7bfd462770abb6ef",
          "sha1": "63da5cd8a1fefe2891bd075e65f974916a7918d7",
          "md5": "634a785efba83eade1ebd84fc41942c4"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-androidx-compose",
          "version": {
            "requires": "3.5.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-kotlinx-serialization",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.kizitonwose.calendar",
          "module": "compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.mikepenz",
          "module": "multiplatform-markdown-renderer-android",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.github.afreakyelf",
          "module": "Pdf-Viewer",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.ramani-maps",
          "module": "ramani-maplibre",
          "version": {
            "requires": "0.9.0"
          }
        },
        {
          "group": "org.maplibre.gl",
          "module": "android-plugin-markerview-v9",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-jvm",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.13.45"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-i18n",
          "version": {
            "requires": "1.0.0-alpha01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "ux-native-android-sdk-1.8.1.aar",
          "url": "ux-native-android-sdk-1.8.1.aar",
          "size": 5234554,
          "sha512": "36045aded3c534e4a06e5db43c434131c6ae6982e617773e772b3d72b9b212658213b7a0ec0bff39bd831b9c9ecd4161766b6b9afb18ba0560ec6d6c9663aeb9",
          "sha256": "35579cc1fe36c276be0fe99ea2a9ef7e077ee4515d9f00fb7bfd462770abb6ef",
          "sha1": "63da5cd8a1fefe2891bd075e65f974916a7918d7",
          "md5": "634a785efba83eade1ebd84fc41942c4"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ux-native-android-sdk-1.8.1-sources.jar",
          "url": "ux-native-android-sdk-1.8.1-sources.jar",
          "size": 572785,
          "sha512": "62c905bba99667fe47b481e769e39f328470aa7aef32d876d0ea3caedf0872e34d0ed1e53e0f604a2fd6b099df3b4bf0dfa8d3c6d94cb30ffe0b52897115ae3c",
          "sha256": "e487b971f0fcb47fdca61b1605bcba2ec7bf62790587f0ebe5794be6896ff5b1",
          "sha1": "c2473e300425e1e492377639395798dc502e2345",
          "md5": "b13e59812831301e80083adfd7b27875"
        }
      ]
    }
  ]
}
