{
  "formatVersion": "1.1",
  "component": {
    "group": "meili.travel",
    "module": "ux-native-android-sdk",
    "version": "1.10.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "ux-native-android-sdk-1.10.1.aar",
          "url": "ux-native-android-sdk-1.10.1.aar",
          "size": 4871799,
          "sha512": "5f818666a4eb86bd123ca90db730e7df25a2fe5de02a0df783972d59691b5558f39d2a68415c8714e26589c9a9146b70e0cbe50673a114155a1b387723bb894d",
          "sha256": "c682669746d4bdb2a9e4d42891fe77a33ba8db6c01e40a029e4889dea892920d",
          "sha1": "3c831b73e5b052de783e3723737d58fde4d2683a",
          "md5": "25185db955932a76c12eb6e69b394796"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-kotlinx-serialization",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.kizitonwose.calendar",
          "module": "compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.mikepenz",
          "module": "multiplatform-markdown-renderer-android",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.github.afreakyelf",
          "module": "Pdf-Viewer",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.maplibre.gl",
          "module": "android-sdk",
          "version": {
            "requires": "11.8.1"
          }
        },
        {
          "group": "org.maplibre.gl",
          "module": "android-plugin-annotation-v9",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-jvm",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.13.45"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "ux-native-android-sdk-1.10.1.aar",
          "url": "ux-native-android-sdk-1.10.1.aar",
          "size": 4871799,
          "sha512": "5f818666a4eb86bd123ca90db730e7df25a2fe5de02a0df783972d59691b5558f39d2a68415c8714e26589c9a9146b70e0cbe50673a114155a1b387723bb894d",
          "sha256": "c682669746d4bdb2a9e4d42891fe77a33ba8db6c01e40a029e4889dea892920d",
          "sha1": "3c831b73e5b052de783e3723737d58fde4d2683a",
          "md5": "25185db955932a76c12eb6e69b394796"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ux-native-android-sdk-1.10.1-sources.jar",
          "url": "ux-native-android-sdk-1.10.1-sources.jar",
          "size": 610085,
          "sha512": "b1d776f1950ffd40a2d952a74473c6de531c6969ae00b7effb8d3ea1e88847b7cbb424cb78e6a43c0bd80a8d671c6a3085db7410edcd84e0bcd97c81c0ac8504",
          "sha256": "3688265707b9be821eb0b72f9ae337d1efee5b59654cc63050d8c4269f0378b0",
          "sha1": "2979834b64965c8e3d334b964a759383d73f1f0c",
          "md5": "9355db86fc9bfbd2557b75479bb62023"
        }
      ]
    }
  ]
}
