{
  "formatVersion": "1.1",
  "component": {
    "group": "com.meili.travel",
    "module": "meili-car-sdk",
    "version": "1.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "meili-car-sdk-1.12.0.aar",
          "url": "meili-car-sdk-1.12.0.aar",
          "size": 5114423,
          "sha512": "1710399ee8f9fb8df5979167690dd956d6eb17d16acb9bde0b01eeb385e5d2adf9673a502d86a88a77b6cc16bcee7675288b01f612f5fb7300d4302459128dda",
          "sha256": "614b18a65066c025d319b1eaa83a24baa8f5c5dc34a1edc9251e3b316994d221",
          "sha1": "5ea3d37ce7a95cb8eb45b44171bb2ac8b0de4ad1",
          "md5": "3997ff1c9ab13f86472ca97e283e51c3"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.8.9"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation-layout",
          "version": {
            "requires": "1.10.6"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-kotlinx-serialization",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.kizitonwose.calendar",
          "module": "compose",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "com.mikepenz",
          "module": "multiplatform-markdown-renderer-android",
          "version": {
            "requires": "0.24.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.github.afreakyelf",
          "module": "Pdf-Viewer",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.6.1"
          }
        },
        {
          "group": "org.maplibre.gl",
          "module": "android-sdk",
          "version": {
            "requires": "11.8.1"
          }
        },
        {
          "group": "org.maplibre.gl",
          "module": "android-plugin-annotation-v9",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common-jvm",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "com.googlecode.libphonenumber",
          "module": "libphonenumber",
          "version": {
            "requires": "8.13.45"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "meili-car-sdk-1.12.0.aar",
          "url": "meili-car-sdk-1.12.0.aar",
          "size": 5114423,
          "sha512": "1710399ee8f9fb8df5979167690dd956d6eb17d16acb9bde0b01eeb385e5d2adf9673a502d86a88a77b6cc16bcee7675288b01f612f5fb7300d4302459128dda",
          "sha256": "614b18a65066c025d319b1eaa83a24baa8f5c5dc34a1edc9251e3b316994d221",
          "sha1": "5ea3d37ce7a95cb8eb45b44171bb2ac8b0de4ad1",
          "md5": "3997ff1c9ab13f86472ca97e283e51c3"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "meili-car-sdk-1.12.0-sources.jar",
          "url": "meili-car-sdk-1.12.0-sources.jar",
          "size": 689843,
          "sha512": "8c497ed43e9758d435b2d3fe6f8722dbd4d544ee9c860c51cba9df9e4849e46e98b221f10e9fe59b574ae7535a7dee2868b65691d4967db3305a7f8f597ae3c8",
          "sha256": "ab2fef78684f4c881406f1f7888f2989e932cfed72d75744fff2f1111e57fc80",
          "sha1": "6bf9cbfdf658f38a0b26d94bb4107feaca0a18c2",
          "md5": "9f98ee4113382803a7033f7d01a4e36f"
        }
      ]
    }
  ]
}
